# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    app.manager.oauth_client:
        class: Core\ApiBundle\Entity\Manager\OAuthClientManager
        arguments: ["@fos_oauth_server.entity_manager", "%fos_oauth_server.model.client.class%"]
