# core_user_homepage:
#     path:     /welcome
#     defaults: { _controller: CoreUserBundle:User:index }
core_user_login:
    path: /login
    defaults: { _controller: CoreUserBundle:User:login }

core_user_registration:
    path: /register
    defaults: { _controller: CoreUserBundle:User:registration }

core_account_activation:
    path: /activation/{id}/{date}
    defaults: { _controller: CoreUserBundle:User:activateLink }

core_account_send_link:
    path: /reactivate/{id}
    defaults: { _controller: CoreUserBundle:User:reactivateLink }

user:
    type: rest
    resource: Core\UserBundle\Controller\Rest\UserController